[project]
name = "ayyadteleuserbot"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "TgCrypto-pyrofork",
    "kurigram",
    "pydub",
    "googletrans",
    "redis[hiredis]",
    "pytz",
    "pyTelegramBotAPI",
    "patchright",
    "py-tgcalls",
    "ayyad_apis @ git+https://github.com/ahmedayyad-dev/Ayyad-APIs.git",
    "py-yt-search",
    "python-dotenv",
]

[tool.uv]
managed = true
